name: Build and Push Docker image

on:
  push:
    branches: [ main ]  # Run this workflow on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use latest Ubuntu runner
    steps:
      - uses: actions/checkout@v3  # Step 1: Check out your code

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Securely use your Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Securely use your Docker password or token

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: navyasree143/ml-devops-demo:latest  # Replace with your Docker Hub username!
